const app=document.getElementById("app");
const S={name:"",code:"",lat:null,lon:null,radius:5,filter:"any",rs:[],votes:{},members:[],loading:false};
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const btn=(t,f,secondary=false)=>`<button class="btn ${secondary?"secondary":"primary"}" onclick="${f}">${t}</button>`;
const icon=t=>t==="cafe"?"☕":t==="fast_food"?"🍔":"🍽️";
function shell(content,back=""){app.innerHTML=`<div class="app"><header><button class="brand" onclick="home()"><span>🍴</span><b>Where Should We Eat?</b></button><div class="header-actions">${back?`<button class="icon-btn" onclick="${back}">←</button>`:""}<span class="live">● LIVE</span></div></header>${content}<footer>Free restaurant data · OpenStreetMap contributors</footer></div>`}
function home(){shell(`<section class="hero"><div class="hero-badge">YOUR GROUP FOOD DECISION MAKER</div><div class="hero-icon">🍽️</div><h1>Stop arguing.<br><span>Just eat.</span></h1><p>Find nearby places, vote with your friends, and let the group decide.</p><div class="hero-actions">${btn("📍 Find food near me","solo()")}${btn("👥 Create a group","createGroup()",true)}${btn("🔑 Join a group","joinGroup()",true)}</div><div class="trust"><span>✓ Free data</span><span>✓ No account</span><span>✓ Real locations</span></div></section>`)}
function solo(){S.name="You";S.code="SOLO";filters()}
function createGroup(){shell(`<section class="narrow"><div class="eyebrow">GROUP MODE</div><h2>Create your food group</h2><p>Pick a name so your friends know who's voting.</p><div class="panel form"><label>Your name<input id="name" maxlength="40" placeholder="Ali" autocomplete="name"></label>${btn("Create group →","makeGroup()")}</div></section>`,"home()")}
async function post(url,data){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||"Something went wrong");return x}
async function makeGroup(){try{S.name=document.getElementById("name").value.trim()||"Host";const x=await post("/api/session/create",{name:S.name});S.code=x.code;S.members=[S.name];group()}catch(e){alert(e.message)}}
function joinGroup(){shell(`<section class="narrow"><div class="eyebrow">GROUP MODE</div><h2>Join your friends</h2><p>Enter the six-character code from the group host.</p><div class="panel form"><label>Group code<input id="code" maxlength="6" placeholder="ABC123" autocapitalize="characters"></label><label>Your name<input id="name" maxlength="40" placeholder="Ali"></label>${btn("Join group →","doJoin()")}</div></section>`,"home()")}
async function doJoin(){try{S.code=document.getElementById("code").value.trim().toUpperCase();S.name=document.getElementById("name").value.trim()||"Guest";const x=await post("/api/session/join",{code:S.code,name:S.name});S.members=x.members;group()}catch(e){alert(e.message)}}
function group(){shell(`<section class="narrow"><div class="eyebrow">YOUR GROUP</div><div class="code-card"><div><small>GROUP CODE</small><strong>${S.code}</strong></div><button onclick="navigator.clipboard?.writeText('${S.code}');this.textContent='Copied ✓';setTimeout(()=>this.textContent='Copy code',1200)">Copy code</button></div><div class="panel people"><div class="section-title"><b>People in this group</b><span id="memberCount">${S.members.length}</span></div><div class="chips">${S.members.map(n=>`<span>👤 ${esc(n)}</span>`).join("")}</div></div>${btn("Start finding food →","filters()")}<p class="tiny">Send the code to your friends, then everyone can vote from their own phone.</p></section>`,"home()")}
function filters(){shell(`<section class="narrow"><div class="eyebrow">STEP 1 OF 2</div><h2>What are you in the mood for?</h2><p>We'll search around your current location.</p><div class="filter-grid">${["any","restaurant","fast_food","cafe"].map(x=>`<button class="filter ${S.filter===x?"selected":""}" onclick="S.filter='${x}';filters()"><span>${x==="any"?"✨":icon(x)}</span><b>${x==="any"?"Anything":x==="restaurant"?"Restaurants":x==="fast_food"?"Fast food":"Cafés"}</b></button>`).join("")}</div><div class="panel range"><div><b>Search radius</b><strong><span id="km">${S.radius}</span> km</strong></div><input type="range" min="1" max="20" value="${S.radius}" oninput="S.radius=+this.value;km.textContent=this.value"><div class="range-labels"><span>1 km</span><span>20 km</span></div></div>${btn("📍 Find places near me","locate()")}</section>`,"home()")}
function locate(){shell(`<section class="loading"><div class="loading-icon">📍</div><div class="eyebrow">STEP 2 OF 2</div><h2>Finding your location</h2><p>Allow location access when your browser asks.</p><span class="spinner"></span></section>`);if(!navigator.geolocation)return locErr("Your browser doesn't support location.");navigator.geolocation.getCurrentPosition(p=>{S.lat=p.coords.latitude;S.lon=p.coords.longitude;load()},e=>locErr(e.code===1?"Location access was denied. Allow it for this site and try again.":"We couldn't get your location. Try again."),{enableHighAccuracy:true,timeout:30000,maximumAge:120000})}
function locErr(m){shell(`<section class="narrow center"><div class="big-icon">📍</div><h2>Location needed</h2><div class="error">${esc(m)}</div>${btn("Try again","locate()")}</section}`,"filters()")}
async function load(){shell(`<section class="loading"><div class="loading-icon">🔎</div><div class="eyebrow">SEARCHING</div><h2>Finding the good stuff…</h2><p>Checking free OpenStreetMap data within ${S.radius} km.</p><span class="spinner"></span></section>`);try{const x=await post("/api/restaurants",{lat:S.lat,lon:S.lon,radius:S.radius});S.rs=x.restaurants.filter(r=>S.filter==="any"||r.type===S.filter);render()}catch(e){shell(`<section class="narrow center"><div class="big-icon">😵</div><h2>Search is busy</h2><div class="error">${esc(e.message)}</div>${btn("Try again","load()")}</section>`,"filters()")}}
function restaurantCard(r){const v=S.votes[r.id];return `<article class="restaurant"><div class="restaurant-top"><div class="food-icon">${icon(r.type)}</div><div class="distance">${r.distance} km</div></div><div class="restaurant-body"><div class="restaurant-title"><h3>${esc(r.name)}</h3><span class="type-tag">${r.type==="fast_food"?"FAST FOOD":r.type==="cafe"?"CAFÉ":"RESTAURANT"}</span></div><p class="cuisine">${esc(r.cuisine||"Local food")}</p>${r.address?`<p class="meta">📍 ${esc(r.address)}</p>`:""}${r.opening?`<p class="meta open">● Hours: ${esc(r.opening)}</p>`:""}<div class="vote-row"><button class="${v===1?"chosen":""}" onclick="vote('${r.id}',1)">❤️<small>I'd eat here</small></button><button class="${v===0?"chosen":""}" onclick="vote('${r.id}',0)">😐<small>Maybe</small></button><button class="${v===-1?"chosen":""}" onclick="vote('${r.id}',-1)">✕<small>Not for me</small></button></div><button class="map-btn" onclick="window.open('https://www.openstreetmap.org/?mlat=${r.lat}&mlon=${r.lon}#map=18/${r.lat}/${r.lon}','_blank')">View on map ↗</button></div></article>`}
function render(){if(!S.rs.length){shell(`<section class="narrow center"><div class="big-icon">🔍</div><h2>No matches yet</h2><p>Try "Anything" or increase your search radius.</p>${btn("Change filters","filters()")}</section>`,"filters()");return}shell(`<section><div class="results-head"><div><div class="eyebrow">NEAR YOU</div><h2>${S.rs.length} places found</h2><p>Vote on the ones you'd actually consider.</p></div><button class="refresh" onclick="load()">↻</button></div><div class="cards">${S.rs.map(restaurantCard).join("")}</div>${btn(S.code==="SOLO"?"🏆 Pick my best match":"🏆 Reveal the group winner","results()")}<button class="text-btn" onclick="filters()">Change filters</button></section>`,"filters()")}
async function vote(id,v){S.votes[id]=v;if(S.code!=="SOLO"){try{await post("/api/vote",{code:S.code,member:S.name,restaurant_id:id,value:v})}catch(e){}}render()}
async function results(){let group={};if(S.code!=="SOLO"){try{const x=await post("/api/results",{code:S.code});x.results.forEach(r=>group[r.restaurant_id]=(r.likes||0)*3+(r.maybes||0)-(r.dislikes||0)*3)}catch(e){}}const ranked=S.rs.map(r=>{const personal=S.votes[r.id]||0;const score=100-r.distance*5+(S.code==="SOLO"?(personal===1?55:personal===-1?-65:personal===0?12:0):(group[r.id]||0)*12);return {...r,score}}).sort((a,b)=>b.score-a.score);const w=ranked[0];shell(`<section class="winner"><div class="winner-trophy">🏆</div><div class="eyebrow">THE GROUP DECISION</div><h1>You're eating at</h1><article class="winner-card"><div class="winner-icon">${icon(w.type)}</div><div><span class="best">🔥 BEST MATCH</span><h2>${esc(w.name)}</h2><p>${esc(w.cuisine||"Local food")} · ${w.distance} km away</p>${w.address?`<small>📍 ${esc(w.address)}</small>`:""}</div></article><div class="winner-actions">${btn("📍 Get directions",`window.open('https://www.openstreetmap.org/?mlat=${w.lat}&mlon=${w.lon}#map=18/${w.lat}/${w.lon}','_blank')`)}${btn("Keep voting","render()",true)}</div></section>`,"render()")}
home();